# Generated by Django 5.2.4 on 2026-07-16 09:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=30, unique=True, verbose_name='Numero')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Data')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('in_progress', 'In lavorazione'), ('completed', 'Completato'), ('sent', 'Inviato'), ('archived', 'Archiviato')], db_index=True, default='draft', max_length=20, verbose_name='Stato')),
                ('client_contact', models.CharField(blank=True, max_length=150, verbose_name='Referente cliente')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Note interne')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Note visibili al cliente')),
                ('feasibility', models.CharField(choices=[('to_check', 'Da verificare'), ('internal', 'Fattibile internamente'), ('external', 'Fattibile con lavorazioni o acquisti esterni'), ('not_feasible', 'Non fattibile')], db_index=True, default='to_check', max_length=20, verbose_name='Fattibilita')),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prezzo commerciale offerto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='Autore')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='catalog.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'preventivo',
                'verbose_name_plural': 'preventivi',
                'ordering': ['-date', '-id'],
                'permissions': [('duplicate_quote', 'Puo duplicare preventivi'), ('archive_quote', 'Puo archiviare preventivi'), ('generate_quote_pdf', 'Puo generare PDF preventivi')],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='Codice')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantita')),
                ('description', models.CharField(blank=True, db_index=True, max_length=250, verbose_name='Descrizione')),
                ('revision', models.CharField(blank=True, max_length=50, verbose_name='Revisione')),
                ('dimensions', models.CharField(blank=True, max_length=150, verbose_name='Dimensioni')),
                ('technical_notes', models.TextField(blank=True, verbose_name='Note tecniche')),
                ('feasibility', models.CharField(choices=[('to_check', 'Da verificare'), ('internal', 'Fattibile internamente'), ('external', 'Fattibile con lavorazioni o acquisti esterni'), ('not_feasible', 'Non fattibile')], default='to_check', max_length=20, verbose_name='Fattibilita articolo')),
                ('feasibility_manually_set', models.BooleanField(default=False, editable=False)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'articolo',
                'verbose_name_plural': 'articoli',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Fase attiva')),
                ('notes', models.TextField(blank=True, verbose_name='Note fase')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name='Ordine')),
                ('internal_answer', models.CharField(choices=[('yes', 'Si'), ('no', 'No'), ('to_check', 'Da verificare')], default='to_check', max_length=20, verbose_name='Si riesce a realizzare internamente?')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_phases', to='catalog.phasedefinition')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='quotes.quoteitem')),
            ],
            options={
                'verbose_name': 'fase articolo',
                'verbose_name_plural': 'fasi articolo',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Peso (kg) per pezzo')),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Costo al kg acquisito')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.material', verbose_name='Materiale')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='quotes.quoteitem')),
            ],
            options={
                'verbose_name': 'materiale articolo',
                'verbose_name_plural': 'materiali articolo',
            },
        ),
        migrations.CreateModel(
            name='TimeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Minuti lavorazione')),
                ('setup_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Minuti attrezzaggio')),
                ('operators_snapshot', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Operatori')),
                ('time_basis', models.CharField(choices=[('per_piece', 'Per singolo pezzo'), ('lot', 'Per intero lotto')], default='per_piece', max_length=20, verbose_name='Riferimento tempo')),
                ('resource_name_snapshot', models.CharField(max_length=150, verbose_name='Nome risorsa acquisito')),
                ('hourly_cost_snapshot', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo orario acquisito')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='quotes.itemphase')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='catalog.productionresource', verbose_name='Risorsa')),
            ],
            options={
                'verbose_name': 'operazione temporale',
                'verbose_name_plural': 'operazioni temporali',
            },
        ),
        migrations.CreateModel(
            name='ExternalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('galvanizing', 'Zincatura'), ('cataphoresis', 'Cataforesi'), ('painting', 'Verniciatura'), ('other', 'Altro')], max_length=20, verbose_name='Tipo trattamento')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Descrizione')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='Fornitore')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='quotes.itemphase')),
            ],
            options={
                'verbose_name': 'trattamento esterno',
                'verbose_name_plural': 'trattamenti esterni',
                'constraints': [models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='treatment_cost_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='DirectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Descrizione')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='Fornitore')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Importo')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_costs', to='quotes.itemphase')),
            ],
            options={
                'verbose_name': 'costo diretto',
                'verbose_name_plural': 'costi diretti',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='direct_cost_non_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['code', 'description'], name='quotes_quot_code_c2d80c_idx'),
        ),
        migrations.AddConstraint(
            model_name='quoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='itemphase',
            constraint=models.UniqueConstraint(fields=('item', 'definition'), name='unique_phase_per_item'),
        ),
        migrations.AddConstraint(
            model_name='itemmaterial',
            constraint=models.UniqueConstraint(fields=('item', 'material'), name='unique_material_per_item'),
        ),
        migrations.AddConstraint(
            model_name='itemmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__gt', 0)), name='material_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='timeoperation',
            constraint=models.CheckConstraint(condition=models.Q(('working_minutes__gte', 0)), name='working_minutes_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='timeoperation',
            constraint=models.CheckConstraint(condition=models.Q(('setup_minutes__gte', 0)), name='setup_minutes_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='timeoperation',
            constraint=models.CheckConstraint(condition=models.Q(('operators_snapshot__gte', 1)), name='operation_operators_positive'),
        ),
        migrations.AddConstraint(
            model_name='timeoperation',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_cost_snapshot__gte', 0)), name='operation_cost_non_negative'),
        ),
    ]
