# Generated by Django 5.2.16 on 2026-07-22 08:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def normalize_historical_quotes(apps, schema_editor):
    Quote = apps.get_model('quotes', 'Quote')
    QuoteItem = apps.get_model('quotes', 'QuoteItem')
    QuoteSequence = apps.get_model('quotes', 'QuoteSequence')

    Quote.objects.filter(feasibility='external').update(feasibility='to_check')
    QuoteItem.objects.filter(feasibility='external').update(feasibility='to_check')

    quotes = list(Quote.objects.order_by('date', 'id'))
    for quote in quotes:
        quote.number = f'TEMP-{quote.pk}'
    Quote.objects.bulk_update(quotes, ['number'])

    counters = {}
    for quote in quotes:
        year = quote.date.year
        counters[year] = counters.get(year, 0) + 1
        quote.number = f'PR-{year}-{counters[year]:05d}'
    Quote.objects.bulk_update(quotes, ['number'])
    for year, last_number in counters.items():
        QuoteSequence.objects.update_or_create(year=year, defaults={'last_number': last_number})


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email referente'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_decision',
            field=models.CharField(choices=[('pending', 'Da definire'), ('accepted', 'Accettato'), ('rejected', 'Rifiutato')], db_index=True, default='pending', max_length=20, verbose_name='Esito cliente'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='bureaucracy',
            field=models.BooleanField(default=False, verbose_name='Certificati e burocrazia'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='bureaucracy_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo certificati e burocrazia'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='external_purchases',
            field=models.BooleanField(default=False, verbose_name='Acquisti esterni'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='external_purchases_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo acquisti esterni'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='external_work',
            field=models.BooleanField(default=False, verbose_name='Lavorazioni esterne'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='external_work_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo lavorazioni esterne'),
        ),
        migrations.RunPython(normalize_historical_quotes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='itemmaterial',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo acquisto/kg'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='feasibility',
            field=models.CharField(choices=[('to_check', 'Da verificare'), ('internal', 'Fattibile internamente'), ('not_feasible', 'Non fattibile')], db_index=True, default='to_check', max_length=20, verbose_name='Fattibilita'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Bozza'), ('in_progress', 'In lavorazione'), ('completed', 'Completato'), ('rejected', 'Rifiutato'), ('sent', 'Inviato'), ('archived', 'Archiviato')], db_index=True, default='draft', max_length=20, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='feasibility',
            field=models.CharField(choices=[('to_check', 'Da verificare'), ('internal', 'Fattibile internamente'), ('not_feasible', 'Non fattibile')], default='to_check', max_length=20, verbose_name='Fattibilita articolo'),
        ),
    ]
