# Generated by Django 5.2.4 on 2026-07-16 09:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Ragione sociale')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Referente predefinito')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('address', models.TextField(blank=True, verbose_name='Indirizzo')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clienti',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhaseDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Codice')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('display_order', models.PositiveSmallIntegerField(unique=True, verbose_name='Ordine')),
                ('active', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'fase',
                'verbose_name_plural': 'fasi',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('current_cost_per_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Costo corrente al kg')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'materiale',
                'verbose_name_plural': 'materiali',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_cost_per_kg__gte', 0)), name='material_cost_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='ProductionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('internal_code', models.CharField(blank=True, max_length=50, verbose_name='Codice interno')),
                ('hourly_cost_per_person', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Costo orario per persona')),
                ('default_operators', models.PositiveSmallIntegerField(default=1, verbose_name='Operatori predefiniti')),
                ('resource_type', models.CharField(choices=[('machine', 'Macchina'), ('manual', 'Attivita manuale'), ('fixed', 'Lavorazione fissa')], max_length=20, verbose_name='Tipo risorsa')),
                ('user_selectable', models.BooleanField(default=True, verbose_name="Selezionabile dall'utente")),
                ('active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='catalog.phasedefinition', verbose_name='Fase')),
            ],
            options={
                'verbose_name': 'risorsa produttiva',
                'verbose_name_plural': 'risorse produttive',
                'ordering': ['phase__display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('phase', 'name'), name='unique_resource_per_phase'), models.CheckConstraint(condition=models.Q(('hourly_cost_per_person__gte', 0)), name='resource_cost_non_negative'), models.CheckConstraint(condition=models.Q(('default_operators__gte', 1)), name='resource_operators_positive')],
            },
        ),
    ]
