# Generated by Django 5.2.16 on 2026-07-22 08:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def initialize_configuration_and_contacts(apps, schema_editor):
    SiteConfiguration = apps.get_model('catalog', 'SiteConfiguration')
    Client = apps.get_model('catalog', 'Client')
    ClientContact = apps.get_model('catalog', 'ClientContact')
    SiteConfiguration.objects.get_or_create(pk=1)
    for client in Client.objects.exclude(contact_name=''):
        ClientContact.objects.get_or_create(
            client=client,
            name=client.contact_name,
            email=client.email or '',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Preventivazione e fattibilità', max_length=100, verbose_name='Titolo applicazione')),
                ('company_name', models.CharField(default='Officine Pollastri', max_length=200, verbose_name='Nome azienda')),
                ('address', models.TextField(blank=True, verbose_name='Indirizzo')),
                ('vat', models.CharField(blank=True, max_length=30, verbose_name='Partita IVA')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email azienda')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono azienda')),
                ('terms', models.TextField(blank=True, default='Validità e condizioni da definire.', verbose_name='Condizioni nei PDF cliente')),
                ('logo', models.FileField(blank=True, upload_to='branding/', verbose_name='Logo header e PDF')),
                ('favicon', models.FileField(blank=True, upload_to='branding/', verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#273A84', max_length=7, validators=[django.core.validators.RegexValidator(message='Inserire un colore esadecimale nel formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Colore principale')),
                ('accent_color', models.CharField(default='#00817D', max_length=7, validators=[django.core.validators.RegexValidator(message='Inserire un colore esadecimale nel formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Colore secondario')),
                ('lan_enabled', models.BooleanField(default=False, help_text="Se attivo, gli altri dispositivi della stessa rete possono usare l'applicazione tramite l'indirizzo del PC server.", verbose_name='Accesso dalla rete LAN')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima modifica')),
            ],
            options={
                'verbose_name': 'configurazione azienda e rete',
                'verbose_name_plural': 'configurazione azienda e rete',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Nome referente')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='catalog.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'referente cliente',
                'verbose_name_plural': 'referenti clienti',
                'ordering': ['client__name', 'name', 'email'],
                'constraints': [models.UniqueConstraint(fields=('client', 'name', 'email'), name='unique_contact_per_client_email')],
            },
        ),
        migrations.RunPython(initialize_configuration_and_contacts, migrations.RunPython.noop),
    ]
