# Generated by Django 5.2.16 on 2026-07-23 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_siteconfiguration_clientcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='lan_enabled',
        ),
        migrations.CreateModel(
            name='LanDeviceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, unpack_ipv4=True, verbose_name='Indirizzo IP')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('allowed', 'Sì, autorizzato'), ('denied', 'No, bloccato')], db_index=True, default='pending', max_length=10, verbose_name='Accesso')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Prima richiesta')),
                ('last_seen_at', models.DateTimeField(verbose_name='Ultima richiesta')),
                ('request_count', models.PositiveIntegerField(default=1, verbose_name='Richieste rilevate')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima decisione')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lan_access_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Decisione di')),
            ],
            options={
                'verbose_name': 'accesso dispositivo LAN',
                'verbose_name_plural': 'accessi dispositivi LAN',
                'ordering': ('-last_seen_at', 'ip_address'),
            },
        ),
    ]
