# Generated by Django 5.2.16 on 2026-07-23 08:57

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_siteconfiguration_lan_enabled_landeviceaccess'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clientcontact',
            constraint=models.UniqueConstraint(models.F('client'), django.db.models.functions.text.Lower('name'), name='unique_contact_name_per_client_ci'),
        ),
        migrations.AddConstraint(
            model_name='clientcontact',
            constraint=models.UniqueConstraint(models.F('client'), django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='unique_contact_email_per_client_ci'),
        ),
    ]
